name: CI
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm install web-ext
      - run: npm run upload
        env:
          CID: ${{ secrets.CLIENT_ID }}
          CS: ${{ secrets.CLIENT_SECRET }}
          RT: ${{ secrets.REFRESH_TOKEN }}
